apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: prod

resources:
- ../../base

labels:
- pairs:
    app.kubernetes.io/environment: prod

images:
- name: ymonterom/prueba-tecnica-apap
  newName: ymonterom/prueba-tecnica-apap
  newTag: 20260329-9d12c0a

patches:
- path: patch-replicas.yml
  target:
    kind: Deployment
    name: prueba-tecnica-apap
- path: patch-ingress.yaml
  target:
    kind: Ingress
    name: prueba-tecnica-apap
- path: patch-certificate.yaml
  target:
    kind: Certificate
    name: prueba-tecnica-apap-tls
