apiVersion: apps/v1
kind: Deployment
metadata:
  name: prueba-tecnica-apap
spec:
  replicas: 3
  template:
    spec:
      containers:
        - name: prueba-tecnica-apap
          env:
            - name: NODE_ENV
              value: "production"
          resources:
            requests:
              cpu: "200m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"