apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prueba-apap-qa
  namespace: argocd
  labels:
    app.kubernetes.io/name: prueba-tecnica-apap
    app.kubernetes.io/environment: qa
  finalizers:
    - resources-finalizer.argocd.io
spec:
  project: default
  source:
    repoURL: https://github.com/yoderickmejia/PRUEBA_APAP.git
    targetRevision: qa
    path: k8s/overlays/qa
  destination:
    server: https://kubernetes.default.svc
    namespace: qa
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - ApplyOutOfSyncOnly=true
    retry:
      limit: 3
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  revisionHistoryLimit: 5
