
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: prueba-tecnica-apap-tls
spec:
  secretName: prueba-tecnica-apap-tls
  issuerRef:
    name: selfsigned-issuer
    kind: ClusterIssuer
  commonName: "20-245-96-137.sslip.io"
  dnsNames:
    - "20-245-96-137.sslip.io"
    - "dev.20-245-96-137.sslip.io"