
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: prueba-tecnica-apap-tls
spec:
  secretName: prueba-tecnica-apap-tls
  issuerRef:
    name: selfsigned-issuer
    kind: ClusterIssuer
  commonName: "app.example.com"
  dnsNames:
    - "app.example.com"