apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: prueba-tecnica-apap
  labels:
    app.kubernetes.io/name: prueba-tecnica-apap
    app.kubernetes.io/component: secret
spec:
  # Frecuencia de sincronización con el backend de secretos
  refreshInterval: 1h
  secretStoreRef:
    # Referencia al SecretStore configurado para este namespace
    name: prueba-tecnica-apap-store
    kind: SecretStore
  target:
    # Nombre del Secret de Kubernetes que se creará/actualizará
    name: prueba-tecnica-apap-secrets
    creationPolicy: Owner
    template:
      type: Opaque
  data:
    - secretKey: NODE_ENV
      remoteRef:
        key: prueba-tecnica-apap
        property: node_env
    - secretKey: PORT
      remoteRef:
        key: prueba-tecnica-apap
        property: port
    - secretKey: API_SECRET
      remoteRef:
        key: prueba-tecnica-apap
        property: api_secret
