apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: prueba-tecnica-apap-store
  labels:
    app.kubernetes.io/name: prueba-tecnica-apap
    app.kubernetes.io/component: secret-store
spec:
  provider:
    # Configurado para HashiCorp Vault.
    # Reemplaza VAULT_ADDR con la URL de tu instancia de Vault.
    vault:
      server: "https://vault.example.com"
      path: "secret"
      version: "v2"
      auth:
        # Autenticación mediante Kubernetes Service Account
        kubernetes:
          mountPath: "kubernetes"
          role: "prueba-tecnica-apap"
          serviceAccountRef:
            name: prueba-tecnica-apap
