apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev

resources:
- ../../base

labels:
- pairs:
    app.kubernetes.io/environment: dev
  includeSelectors: false

images:
- name: ymonterom/prueba-tecnica-apap
  newName: ymonterom/prueba-tecnica-apap
  newTag: dev-20260329-7d078e2

patches:
- path: patch-replicas.yml
  target:
    kind: Deployment
    name: prueba-tecnica-apap
- path: patch-ingress.yaml
  target:
    kind: Ingress
    name: prueba-tecnica-apap
- path: patch-certificate.yaml
  target:
    kind: Certificate
    name: prueba-tecnica-apap-tls
