apiVersion: apps/v1
kind: Deployment
metadata:
  name: prueba-tecnica-apap
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: prueba-tecnica-apap
          env:
            - name: NODE_ENV
              value: "development"
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "250m"
              memory: "256Mi"