apiVersion: apps/v1
kind: Deployment
metadata:
  name: prueba-tecnica-apap
spec:
  replicas: 2
  template:
    spec:
      containers:
        - name: prueba-tecnica-apap
          env:
            - name: NODE_ENV
              value: "staging"
          resources:
            requests:
              cpu: "150m"
              memory: "192Mi"
            limits:
              cpu: "300m"
              memory: "384Mi"